#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OnBoard.Resource", IsApplication=true)]

namespace OnBoard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int black = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int gray = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int gray_silver = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int login_dialog_background = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int osb_error_title_bg = 2131034135;
			
			// aapt resource value: 0x7f050023
			public const int osb_favorite_no_file_desc_bg = 2131034147;
			
			// aapt resource value: 0x7f05000e
			public const int osb_font_black = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int osb_font_light_gray = 2131034128;
			
			// aapt resource value: 0x7f050027
			public const int osb_font_progress_text = 2131034151;
			
			// aapt resource value: 0x7f05000f
			public const int osb_font_white = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int osb_green_dark = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int osb_green_light = 2131034129;
			
			// aapt resource value: 0x7f05002b
			public const int osb_intro_sign_in_button_enable_bg = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int osb_intro_sign_up_button_enable_bg = 2131034156;
			
			// aapt resource value: 0x7f05001d
			public const int osb_list_font_big = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int osb_list_font_small = 2131034142;
			
			// aapt resource value: 0x7f050026
			public const int osb_list_selector_bg = 2131034150;
			
			// aapt resource value: 0x7f050015
			public const int osb_list_separator = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int osb_login_button_disabled_bg = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int osb_login_button_disabled_font = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int osb_login_button_enabled_bg = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int osb_login_button_enabled_font = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int osb_login_link_font = 2131034138;
			
			// aapt resource value: 0x7f05001f
			public const int osb_music_button = 2131034143;
			
			// aapt resource value: 0x7f050025
			public const int osb_music_player_seek_bg = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int osb_music_player_seek_color = 2131034148;
			
			// aapt resource value: 0x7f050020
			public const int osb_passcode_btn_color = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int osb_passcode_btn_divider = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int osb_passcode_btn_font_color = 2131034145;
			
			// aapt resource value: 0x7f050016
			public const int osb_pending_status_layout = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int osb_screen_bg = 2131034125;
			
			// aapt resource value: 0x7f05002a
			public const int osb_search_button_disable_bg = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int osb_search_button_enable_bg = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int osb_search_text_bg = 2131034152;
			
			// aapt resource value: 0x7f050013
			public const int osb_section_bg = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int osb_section_font = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int solid_blue = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int solid_green = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int solid_red = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int solid_yellow = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int text_color_dark = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int text_header1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int text_header2 = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int transparent = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int white = 2131034118;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06001c
			public const int dialog_header_top_bottom_padding = 2131099676;
			
			// aapt resource value: 0x7f060014
			public const int gallery_header_padding = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int list_item_top_bottom_padding = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int list_margin_left = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int photo_crop_stroke_width = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int photo_crop_width = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int photo_page_margin = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int photo_preview_size = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int quick_action_padding = 2131099678;
			
			// aapt resource value: 0x7f06000d
			public const int text_size_auto_sync_dialog = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int text_size_auto_sync_dialog_header = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int text_size_button = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int text_size_dialog_header = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int text_size_favorite_no_file = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int text_size_large = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int text_size_list_normal = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int text_size_list_small = 2131099651;
			
			// aapt resource value: 0x7f06001a
			public const int text_size_music_title = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int text_size_music_title_large = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int text_size_normal = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int text_size_passcode_button = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int text_size_passcode_button_large = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int text_size_passcode_edit = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int text_size_screen_header = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int text_size_section_header = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int text_size_small = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int text_size_xlarge = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int thumbPadding = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int thumbSize = 2131099666;
			
			// aapt resource value: 0x7f06001d
			public const int toast_top_padding = 2131099677;
			
			// aapt resource value: 0x7f060000
			public const int window_title_height = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020008
			public const int blue = 2130837512;
			
			// aapt resource value: 0x7f020000
			public const int carousel_indicator_selected = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int carousel_indicator_unselected = 2130837505;
			
			// aapt resource value: 0x7f020009
			public const int green = 2130837513;
			
			// aapt resource value: 0x7f020002
			public const int intro_image_1 = 2130837506;
			
			// aapt resource value: 0x7f020007
			public const int red = 2130837511;
			
			// aapt resource value: 0x7f020003
			public const int screenOne = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int screenThree = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int screenTwo = 2130837509;
			
			// aapt resource value: 0x7f02000b
			public const int translucent_background = 2130837515;
			
			// aapt resource value: 0x7f020006
			public const int widget_radio_button = 2130837510;
			
			// aapt resource value: 0x7f02000a
			public const int yellow = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090002
			public const int carousel_indicator_layout = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int myPager = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int rootView = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FirstFragment = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SecondFragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ThirdFragment = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppBaseTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int AppTheme = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int Theme_NoTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
